baseURL = "https://xudashuai.blog"
theme = "pure"
title = "许大帅Aiden's Blog"
copyright = "CC BY 4.0 CN"
defaultContentLanguage = "zh"
footnoteReturnLinkContents = "↩"
hasCJKLanguage = true
paginate = 7
enableEmoji = true
PygmentsCodeFences = false
googleAnalytics = ""

[permalinks]
posts = "/:year/:month/:filename/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[outputs]
home = [ "HTML", "RSS", "SearchIndex" ]

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[[menu.main]]
identifier = "home"
name = "Home"
title = "首页"
url = "/"
weight = 1

[[menu.main]]
identifier = "archives"
name = "Archives"
title = "文章"
url = "/posts/"
weight = 2

[[menu.main]]
identifier = "categories"
name = "Categories"
title = "分类"
url = "/categories/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
title = "标签"
url = "/tags/"
weight = 4

[[menu.main]]
identifier = "about"
name = "About"
title = "关于"
url = "/about/"
weight = 5

[params]
since = 2023
dateFormatToUse = "2006-01-02"
enablePostCopyright = true
copyright_link = "http://creativecommons.org/licenses/by/4.0/deed.zh"
mainSections = [ "posts" ]
enableMathJax = true
sidebar = "right"
widgets = [ "board", "tag_cloud", "category", "tag", "recent_posts" ]

[params.highlightjs]
langs = [ "python", "javascript" ]

[params.tag_cloud]
min = 8
max = 20

[params.menuIcons]
enable = true
home = "icon-home-fill"
archives = "icon-archives-fill"
categories = "icon-folder"
tags = "icon-tags"
repository = "icon-project"
books = "icon-book-fill"
links = "icon-friendship"
about = "icon-cup-fill"

[params.profile]
enabled = true
avatar = "avatar.png"
author = "许大帅Aiden"
author_title = ""
author_description = "Good Good Study, Day Day Up~"
location = "Shanghai, China"
follow = ""

[params.profile.social]
link_tooltip = false

[params.profile.social.links]
github = "https://github.com/dashuaixu"
rss = "/index.xml"

[params.site]
title = "公告"
favicon = "favicon.ico"
board = "<p>enjoy~</p>"

[params.site.logo]
enabled = true
width = 40
height = 40
url = "favicon.ico"

[params.share]
enable = true
sites = "weibo,qq,wechat,facebook,twitter"
mobile_sites = "weibo,qq,qzone"

[params.comment]
disqus = "your_disqus_name"

[params.comment.gitalk]

[params.comment.valine]
placeholder = "enjoy~"
avatar = "mm"
meta = "nick,mail"
pageSize = 10
visitor = false

[params.donate]
enable = false

[params.donate.wechatpay]
qrcode = "donate/wechatpayimg.png"
title = "微信支付"

[params.donate.alipay]
qrcode = "donate/alipayimg.png"
title = "支付宝"

[params.pv.busuanzi]
enable = false

[params.pv.leancloud]
enable = false

[params.postCount]
enable = true
wordcount = true
min2read = true

[params.config]
skin = "theme-white"
layout = "main-center"
excerpt_link = "Read More"
toc = true

[params.search]
enable = true
